# Generated by Django 5.1.5 on 2025-01-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="raktar",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("név", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="reszleg",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("név", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="items",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("barcode", models.IntegerField(max_length=255)),
                ("Description", models.TextField(blank=True, max_length=255)),
                ("Mennyiség", models.IntegerField(default=1)),
                (
                    "Depot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Tárgyak",
                        to="api.raktar",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="raktar",
            name="részleg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raktar",
                to="api.reszleg",
            ),
        ),
    ]
