# Generated by Django 5.2 on 2025-05-22 04:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='profile_images')),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='raktar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('Description', models.TextField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='reszleg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('barcode', models.BigIntegerField()),
                ('Leirás', models.TextField(blank=True, max_length=255)),
                ('Mennyiség', models.IntegerField(default=1)),
                ('Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('muvelet', models.CharField(choices=[('BE', 'Bevétel'), ('KI', 'Kiadás')], default='BE', max_length=2)),
                ('Depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tárgyak', to='api.raktar')),
            ],
        ),
        migrations.AddField(
            model_name='raktar',
            name='részleg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raktarok', to='api.reszleg'),
        ),
    ]
