# Generated by Django 5.1.5 on 2025-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="barcode",
            field=models.IntegerField(),
        ),
    ]
