# Generated by Django 5.2 on 2025-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='barcode',
            field=models.BigIntegerField(),
        ),
    ]
