# Generated by Django 5.1.5 on 2025-01-30 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_items_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="név",
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
