# Generated by Django 5.2 on 2025-07-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transactiontype_account_allowed_divisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
