# Generated by Django 5.1.5 on 2025-01-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_items_név"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raktar",
            name="részleg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raktarok",
                to="api.reszleg",
            ),
        ),
    ]
