# Generated by Django 5.1.5 on 2025-01-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_raktar_részleg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="items",
            old_name="név",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="raktar",
            old_name="név",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="reszleg",
            old_name="név",
            new_name="name",
        ),
    ]
