# Generated by Django 5.2 on 2025-07-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_items_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='egysegar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
