# Generated by Django 5.2 on 2025-07-19 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_items_egysegar'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raktar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_raktarok', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reszleg',
            name='Description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='reszleg',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reszlegek', to=settings.AUTH_USER_MODEL),
        ),
    ]
