# Generated by Django 5.2 on 2025-08-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_items_user_raktar_user_reszleg_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='afa_ertek',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='afa_kulcs',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='brutto_ertek',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='depot_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='egysegar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='mertekegyseg',
            field=models.CharField(default='db', max_length=50),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='netto_ertek',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='termek_megnevezes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
